### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by lgarron** [commonmark/commonmark-spec-web#7]
Chrome will mark http://spec.commonmark.org/dingus/ as "Not secure" starting in October:
https://blog.chromium.org/2017/04/next-steps-toward-more-connection.html

![screen shot 2017-09-18 at 14 27 27](https://user-images.githubusercontent.com/248078/30565584-b0ddbc48-9c7d-11e7-934b-3d112c985ee8.png)

Would it be possible to update commonmark.org and its subdomains to use HTTPS by then?

**Comment by strugee** [comment]
Looks like, as usual, isaacs/github#156 is a blocker for this. (Though as has been said many times on that issue, please don't leave +1s.)

However I can access the spec itself over HTTPS just fine? Not sure what's going on there.

**Comment by jgm** [comment]
I believe this has now been fixed by some behind-the-scenes GitHub changes.
At any rate, visiting the spec website with https now seems to work!

**Comment by strugee** [comment]
Shouldn't someone turn on automatic redirects?

**Comment by lgarron** [comment]
> At any rate, visiting the spec website with https now seems to work!

Indeed, the spec website works over HTTPS!

https://commonmark.org/ still doesn't work, though. :-(
And as @strugee mentioned, it would be best to redirect to HTTPS.

**Comment by jgm** [comment]
Can you tell me how?

**Comment by lgarron** [comment]
There should be an "Enforce HTTPS" checkbox in settings:
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

![](https://blog.github.com/assets/img/2018-05-01-github-pages-custom-domains-enforce-https.png)

**Comment by jgm** [comment]
Done.  I don't have any control over the main commonmark.org site,
that's @coding-horror.

**Comment by strugee** [comment]
Thanks @jgm! This is great.
